export const listaTesis = [
    {
        id:1,
        titulo: "Aplicación de Redes Neuronales Profundas para la detección de la cobertura glaciar en imágenes satelitales óptica y radar de apertura sintética en la Cordillera Blanca, Perú - 2022",
        ruta:'redes-neuronales-profundas',
        descrip:{
            descrip1:'Global Land Ice Measurements from Space (GLIMS) es la comunidad científica internacional en glaciología con iniciativa de monitorear e inventariar los glaciares del mundo, principalmente, utilizando datos de instrumentos ópticos por satélite, vale decir, que este comenzó como un proyecto del equipo científico ASTER y, que a través del tiempo, se ha convertido en una herramienta de monitoreo de los glaciares del mundo, quienes a su vez, han creado una red de colaboradores internacionales que analizan imágenes satelitales de glaciares en sus regiones de especialización usando el método índice Normalizado de Diferenciación de Nieve (NDSI).',
            descrip2:'En el Perú, la entidad responsable de monitorear e inventariar los glaciares de los Andes peruanos es el Instituto Nacional de Investigación en Glaciares y Ecosistemas de Montaña (INAIGEM), “el cual representa el 70% de glaciares tropicales del mundo, con 20 cordilleras nevadas, que, si bien son fuentes hídricas fundamentales, también, son fuentes de catástrofes permanentes” (INAIGEM, 2014). Así mismo, el INAIGEM hizo público un manual metodológico para el mapeo de glaciares mediante el método NDSI.',
            descrip3:'El método NDSI es actualmente el más usado para mapear la cobertura glaciar con un umbral radiométrico igual a 0.4, no obstante, muchas veces, es habitual tomar un umbral mayor o menor a 0.4 con la finalidad de obtener mejores resultados de coincidencia de los frentes glaciares y los límites del contorno glaciar, y es que, generalmente se confunden las coberturas circundantes al hielo glaciar por la similitud espectral de las mismas, principalmente, con los cuerpos de agua. Si bien el método NDSI es muy usado en la actualidad, sus limitaciones basadas en su simplicidad de cálculo, el cual consiste en la diferencia normalizada entre las bandas espectrales verde (G) y el infrarrojo de onda corta (SWIR), lo hace susceptible a errores de clasificación, por ende, se tiene que eliminar manualmente los polígonos clasificados erróneamente como cobertura glaciar, resultando en un proceso lento, tedioso y muy costoso, especialmente si se trata de mapear e inventariar muchos glaciares. Además, si las imágenes satelitales no poseen las bandas del infrarrojo medio o infrarrojo de onda corta, no será posible aplicar el método NDSI.',
            descrip4:'En este contexto, el objetivo de esta investigación es proponer el uso de redes neuronales profundas como una alternativa de cartografiado glaciar al método NDSI. Las redes neuronales profundas son un tipo de Inteligencia Artificial (IA) y paradigma de programación que permite desarrollar algoritmos en el procesamiento de imágenes y reconocimiento de patrones visuales. El modelo de red neuronal profunda estará desarrollado con el lenguaje de programación Python y la librería de Aprendizaje Profundo TensorFlow o PyTorch, para el entrenamiento de la red neuronal se usará la Unidad de Procesamiento Gráfico (GPU) en el entorno de programación de Google Colaboratory o Colab. Para terminar, se exportarán las imágenes segmentadas en formato GeoTIFF o TFRecord para su visualización en la plataforma de Google Earth Engine, de donde, se monitoreará el cambio de la cobertura glaciar de forma automatizada, en consecuencia, tener mapeado e inventariado de forma rápida y precisa los glaciares ayudarán a la gestión de los recursos hídricos en la formulación de soluciones que permitan afrontar la escasez de agua en el futuro.',
        },
        temas:{
            tema1:'Inteligencia Artificial',
            tema2:'Redes Neuronales Artificiales',
            tema3:'Machine Learning',
            tema4:'Teledetección'
        },
        estado:"En desarrollo",
        tipo:'pregrado',
        link:null,
        team:[
            {
                user:'0-rnp-victor-smith-medina-cotrina',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Víctor Smith Medina Cotrina',
                nameUser:'Víctor Medina',
                cargo:'Tesista de pregrado',
                profesion:'Bachiller en Ingeniería Ambiental',
                especialidad:null,
                descripcion:'Bachiller en ingeniería ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM), un apasionado por el aprendizaje automático y la ciencia de datos para la comprensión, monitoreo y predección del cambio ambiental. Particularmente interesado en la programación en redes neuronales artificiales, clasificación de imágenes y detección de objetos aplicados a la investigación en glaciares y a la conservación de Áreas Naturales Protegidas (ANPs).',
                ubicacion:'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                contacto:{
                    correo:'mailto:smith_12_47@hotmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:'https://www.linkedin.com/in/v%C3%ADctor-smith-medina-cotrina-28155159/',
                }
            },
            {
                user:'1-rnp-edwin-anibal-loarte-cadenas',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Edwin Anibal Loarte Cadenas',
                nameUser:'Edwin Anibal',
                cargo:'Asesor e investigador principal',
                profesion:'Ingeniero Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad: 'Máster universitario en Gestión de Recursos Hídricos.',
                descripcion:'Profesional ligado a la investigación en recursos hídricos, glaciología, el cambio climático, conocimientos de análisis de riesgos sobre los ámbitos glaciares, simulación de desbordes de lagunas, con conocimiento de SIG y teledetección aplicados al estudio y monitoreo de los recursos ambientales, procesamiento de imágenes de satélite ópticas y radar. Estudios en gestión de recursos hídricos; capacitación en el campo de la glaciología e hidroglaciología, elaboración de balances de masa, determinación de líneas de equilibrio - ELA, determinación del área superficial, estimación de volúmenes, generación de índices de nieve - NDSI para coberturar área glaciar, índices de agua NDWI para coberturar lagunas, NDVI para coberturas de vegetación, experiencia en implementación de bases de datos espaciales e inventarios de lagunas.',
                contacto:{
                    correo:'mailto:e.loarte@inaigem.gob.pe, eloartecadenas@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:'https://www.linkedin.com/in/edwin-loarte-cadenas-182b3153/',
                    ctvitae: 'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=19929',
                    orcid:'https://orcid.org/0000-0003-3123-1904',
                }
            },
            {
                user:'2-rnp-rolando-cruz-encarnacion',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Rolando Cesai Cruz Encarnación',
                nameUser:'Rolando Cruz',
                cargo:'Co-Asesor',
                profesion:'Ingeniera Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'ANA',
                especialidad:'Maestría en "Técnicas de Gestión del Medio Ambiente y del Territorio" / (2020) Universitat de València y Diplomado en "Gestión Ambiental" (2016) / Universidad Nacional de Ingeniería.',
                descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (V superior) - Ancash, con experiencia en trabajos con comunidades en los Andes peruanos, sistematización, organización y procesamiento de datos glaciológicos y geomáticos aplicados a recursos hídricos, he participado en proyectos de cooperación internacional,  durante mi carrera profesional he participado de las publicaciones de documentos técnicos y manuales metodológicos para el estudio de los glaciares y los ecosistemas de montaña.',
                contacto:{
                    correo:'mailto:yadira.acr@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:"https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=143570",
                    orcid:"https://orcid.org/0000-0001-8229-2753",
                    researchgate:"https://www.researchgate.net/profile/Yadira-Curo"
                },
            },
            {
                user:'3-rnp-francisco-nemecio-castillo-vergara',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Francisco Nemecio Castillo Vergara',
                nameUser:'Francisco Castillo',
                cargo:'Asistente de investigación',
                profesion:'Ingeniero Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad:'Especialización en "Modelamiento hidraulico e hidrologico" - CELAEP-UNMSM y Estudios finalizados en maestría en "Ciencias e Ingeniería con mención en Gestión Ambiental" - UNASAM.',
                descripcion:'Ingeniero Ambiental de la UNASAM (quinto superior) dedicado al uso de las herramientas de teledetección y los sistemas de información geográfica. Investigador en proceso de formación en proyectos multidisciplinarios en temáticas relacionadas a ecosistemas glaciares y periglaciares, con conocimiento en el manejo de equipos y técnicas de monitoreo glaciológico. Fotógrafo aficionado y amante del senderismo en altamontaña.',
                contacto:{
                    correo:'mailto:fcastillouv@unasam.edu.pe',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:'https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=351770571c155d27537e1a415bed?id_investigador=145013',
                    orcid:'https://orcid.org/0000-0002-6799-3495',
                    researchgate:null
                },
            },
        ]
    },
    {
        id:2,
        titulo:"Influencia de El Niño Oscilación del Sur (ENOS) en las velocidades superficiales de los glaciares en la cuenca del río Santa, periodo 2015-2022",
        ruta:'Influencia-de-El-Niño-Oscilación-del-Sur-(ENOS)',
        descrip:{
            descrip1:'En América Latina existe manifestaciones de la variabilidad interanual del clima en El Niño Oscilación del Sur (ENOS), por ello, diversas regiones del mundo estudian los impactos a una escala local, ENOS es responsables de muchos patrones de circulación atmosférica, como son las variables de viento, temperatura y precipitación en América y Europa (Capel, 1999). Así mismo, se observa que, en las últimas décadas, el retroceso de los glaciares a nivel mundial se ha acelerado, debido a los efectos del cambio climático y las intervenciones directas e indirectas de las actividades generadas en las zonas de influencia, este hecho ha suscitado la preocupación científica y ciudadana por el futuro de los glaciares (Useros, 2013).',
            descrip2:'El territorio peruano cuenta con más de 8 mil lagunas distribuidas en 14 departamentos del país formadas como consecuencia del retroceso de los glaciares y el cambio climático (ANA, 2020). El Perú siendo frontera con el océano pacifico donde inicia los eventos de ENOS debido a las variaciones del mar, no es ajeno a sus influencias (Capel, 1999). Dentro del territorio encontramos los glaciares tropicales y debido a las crecientes temperaturas vinculadas al calentamiento global se han reducido hasta un 40% las masas glaciares, lo que genera un incremento del nivel de las aguas en las lagunas. Cada vez que los glaciares se retiran, el hielo es más débil, cayendo en pedazos lo que provoca peligros de avalanchas (ANA, 2022).',
            descrip3:'El Perú cuenta con 20 cordilleras glaciares, de los cuales 18 albergan glaciares blancos y las otras 2 cordilleras están cubiertas por glaciares rocosos. Dentro de las 18 cordilleras, la cordillera Blanca tiene mayor área y volumen aportando 13.8 MMC, entre las unidades hidrográficas a nivel nacional se encuentra la cuenca del río Santa con mayor cobertura glaciar (ANA, 2020).',
            descrip4:'Los glaciares Artesonraju, Shallap y Gueshgue pertenecen a la cuenca del río Santa (Villanueva, 2011), se encuentran en diversos cambios relacionados a los parámetros y condiciones físicas, como desplazamiento y velocidad. Por su ubicación geográfica de cada uno de ellos, es de difícil acceso para realizar mediciones superiores a los 5000 m s.n.m. en este escenario la teledetección es muy importante, ya que ofrece la posibilidad de cuantificar el flujo glaciar en términos de la velocidad superficial, para así poder determinar la influencia de ENOS en la dinámica glaciar, ya que la información obtenida permitirá evaluar la situación actual.',
            descrip5:'La escasa investigación que existe sobre las variaciones y cambios que sufre los glaciares influenciados por ENOS, no nos permite reconocer la situación actual de estos, por lo tanto, puede existir escasez de recursos hídricos, generación de avalanchas, reducción de la producción agrícola y la disminución de la actividad turística, y por ende, la economía del país podría verse afectada.',
            descrip6:'Bajo este contexto, esta investigación tiene como objetivo generar mayor información sobre la velocidad del glaciar influenciado por ENOS, así mismo, reconocer la variación de las velocidades en un período de 7 años.',
        },
        temas:{
            tema1:'Variabilidad climática y fenómenos climáticos ENOS',
            tema2:'Interferometría SAR (InSAR) ',
            tema3:'Interferometría Diferencial SAR (DInSar).',
            tema4:'Teledetección'
        },
        estado:"En desarrollo",
        tipo:'pregrado',
        link:null,
        team:[
            {
                user:'0-enos-emely-consuelo-barreto-jamanca',
                ruta:'Influencia-de-El-Niño-Oscilación-del-Sur-(ENOS)',
                foto:'/section/Clima.jpg',
                name:'Emely Consuelo Barrreto Jamanca',
                nameUser:'Emely Barreto',
                cargo:'Tesista de pregrado',
                profesion:'Ingeniera Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad:null,
                descripcion:'Ingeniera Ambiental de la UNASAM (V superior) - Ancash. Experiencia en estudios de ecología. Participación en proyectos de investigación enfocados al estudio de ecosistemas de montaña, así como en biodiversidad en bosques xéricos y andinos. Conocimiento en tecnologías GIS, manejo de herramientas de estadística ecológica y estimación de la biodiversidad.',
                contacto:{
                    correo:'mailto:mp.alejo.mosquera@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:"https://www.linkedin.com/in/miluska-pamela-alejo-mosquera-91a2bb223",
                    ctvitae:"https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=274222",
                    orcid:"https://orcid.org/0000-0002-6510-7875 ",
                    researchgate:null
                },
            },
            {
                user:'1-enos-edwin-anibal-loarte-cadenas',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Edwin Anibal Loarte Cadenas',
                nameUser:'Edwin Anibal',
                cargo:'Asesor e investigador principal',
                profesion:'Ingeniero Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad: 'Máster universitario en Gestión de Recursos Hídricos.',
                descripcion:'Profesional ligado a la investigación en recursos hídricos, glaciología, el cambio climático, conocimientos de análisis de riesgos sobre los ámbitos glaciares, simulación de desbordes de lagunas, con conocimiento de SIG y teledetección aplicados al estudio y monitoreo de los recursos ambientales, procesamiento de imágenes de satélite ópticas y radar. Estudios en gestión de recursos hídricos; capacitación en el campo de la glaciología e hidroglaciología, elaboración de balances de masa, determinación de líneas de equilibrio - ELA, determinación del área superficial, estimación de volúmenes, generación de índices de nieve - NDSI para coberturar área glaciar, índices de agua NDWI para coberturar lagunas, NDVI para coberturas de vegetación, experiencia en implementación de bases de datos espaciales e inventarios de lagunas.',
                contacto:{
                    correo:'mailto:e.loarte@inaigem.gob.pe, eloartecadenas@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:'https://www.linkedin.com/in/edwin-loarte-cadenas-182b3153/',
                    ctvitae: 'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=19929',
                    orcid:'https://orcid.org/0000-0003-3123-1904',
                }
            },
            {
                user:'2-enos-rolando-cruz-encarnacion',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Rolando Cesai Cruz Encarnación',
                nameUser:'Rolando Cruz',
                cargo:'Co-Asesor',
                profesion:'Ingeniera Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'ANA',
                especialidad:'Maestría en "Técnicas de Gestión del Medio Ambiente y del Territorio" / (2020) Universitat de València y Diplomado en "Gestión Ambiental" (2016) / Universidad Nacional de Ingeniería.',
                descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (V superior) - Ancash, con experiencia en trabajos con comunidades en los Andes peruanos, sistematización, organización y procesamiento de datos glaciológicos y geomáticos aplicados a recursos hídricos, he participado en proyectos de cooperación internacional,  durante mi carrera profesional he participado de las publicaciones de documentos técnicos y manuales metodológicos para el estudio de los glaciares y los ecosistemas de montaña.',
                contacto:{
                    correo:'mailto:yadira.acr@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:"https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=143570",
                    orcid:"https://orcid.org/0000-0001-8229-2753",
                    researchgate:"https://www.researchgate.net/profile/Yadira-Curo"
                },
            },
            {
                user:'3-enos-francisco-nemecio-castillo-vergara',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Francisco Nemecio Castillo Vergara',
                nameUser:'Francisco Castillo',
                cargo:'Asistente de investigación',
                profesion:'Ingeniero Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad:'Especialización en "Modelamiento hidraulico e hidrologico" - CELAEP-UNMSM y Estudios finalizados en maestría en "Ciencias e Ingeniería con mención en Gestión Ambiental" - UNASAM.',
                descripcion:'Ingeniero Ambiental de la UNASAM (quinto superior) dedicado al uso de las herramientas de teledetección y los sistemas de información geográfica. Investigador en proceso de formación en proyectos multidisciplinarios en temáticas relacionadas a ecosistemas glaciares y periglaciares, con conocimiento en el manejo de equipos y técnicas de monitoreo glaciológico. Fotógrafo aficionado y amante del senderismo en altamontaña.',
                contacto:{
                    correo:'mailto:fcastillouv@unasam.edu.pe',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:'https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=351770571c155d27537e1a415bed?id_investigador=145013',
                    orcid:'https://orcid.org/0000-0002-6799-3495',
                    researchgate:null
                },
            },
        ]
    },
    {
        id:3,
        titulo:"Determinación del nivel de influencia de la temperatura en la variación de los espesores de los frentes glaciares en la Cordillera Blanca, periodo 2015-2022",
        ruta:'Determinación-del-nivel-de-influencia-de-la-temperatura-en-la-variación-de-los-espesores-de-los-frentes-glaciares-en-la-Cordillera-Blanca',
        descrip:{
            descrip1:'En América Latina existe manifestaciones de la variabilidad interanual del clima en El Niño Oscilación del Sur (ENOS), por ello, diversas regiones del mundo estudian los impactos a una escala local, ENOS es responsables de muchos patrones de circulación atmosférica, como son las variables de viento, temperatura y precipitación en América y Europa (Capel, 1999). Así mismo, se observa que, en las últimas décadas, el retroceso de los glaciares a nivel mundial se ha acelerado, debido a los efectos del cambio climático y las intervenciones directas e indirectas de las actividades generadas en las zonas de influencia, este hecho ha suscitado la preocupación científica y ciudadana por el futuro de los glaciares (Useros, 2013).',
            descrip2:'El territorio peruano cuenta con más de 8 mil lagunas distribuidas en 14 departamentos del país formadas como consecuencia del retroceso de los glaciares y el cambio climático (ANA, 2020). El Perú siendo frontera con el océano pacifico donde inicia los eventos de ENOS debido a las variaciones del mar, no es ajeno a sus influencias (Capel, 1999). Dentro del territorio encontramos los glaciares tropicales y debido a las crecientes temperaturas vinculadas al calentamiento global se han reducido hasta un 40% las masas glaciares, lo que genera un incremento del nivel de las aguas en las lagunas. Cada vez que los glaciares se retiran, el hielo es más débil, cayendo en pedazos lo que provoca peligros de avalanchas (ANA, 2022).',
            descrip3:'El Perú cuenta con 20 cordilleras glaciares, de los cuales 18 albergan glaciares blancos y las otras 2 cordilleras están cubiertas por glaciares rocosos. Dentro de las 18 cordilleras, la cordillera Blanca tiene mayor área y volumen aportando 13.8 MMC, entre las unidades hidrográficas a nivel nacional se encuentra la cuenca del río Santa con mayor cobertura glaciar (ANA, 2020).',
            descrip4:'Los glaciares Artesonraju, Shallap y Gueshgue pertenecen a la cuenca del río Santa (Villanueva, 2011), se encuentran en diversos cambios relacionados a los parámetros y condiciones físicas, como desplazamiento y velocidad. Por su ubicación geográfica de cada uno de ellos, es de difícil acceso para realizar mediciones superiores a los 5000 m s.n.m. en este escenario la teledetección es muy importante, ya que ofrece la posibilidad de cuantificar el flujo glaciar en términos de la velocidad superficial, para así poder determinar la influencia de ENOS en la dinámica glaciar, ya que la información obtenida permitirá evaluar la situación actual.',
            descrip5:'La escasa investigación que existe sobre las variaciones y cambios que sufre los glaciares influenciados por ENOS, no nos permite reconocer la situación actual de estos, por lo tanto, puede existir escasez de recursos hídricos, generación de avalanchas, reducción de la producción agrícola y la disminución de la actividad turística, y por ende, la economía del país podría verse afectada.',
            descrip6:'Bajo este contexto, esta investigación tiene como objetivo generar mayor información sobre la velocidad del glaciar influenciado por ENOS, así mismo, reconocer la variación de las velocidades en un período de 7 años.',
        },
        temas:{
            tema1:'Variabilidad climática y fenómenos climáticos ENOS',
            tema2:'Interferometría SAR (InSAR) ',
            tema3:'Interferometría Diferencial SAR (DInSar).',
            tema4:'Teledetección'
        },
        estado:"En desarrollo",
        tipo:'pregrado',
        link:null,
        team:[
            {
                user:'0-dfg-thalia-yanina-calixto-lopez',
                ruta:'Determinación-del-nivel-de-influencia-de-la-temperatura-en-la-variación-de-los-espesores-de-los-frentes-glaciares-en-la-Cordillera-Blanca',
                foto:'/section/Clima.jpg',
                name:'Thalía Yanina Calixto Lopez',
                nameUser:'Thalía Calixto',
                cargo:'Tesista de pregrado',
                profesion:'Ingeniera Ambiental',
                ubicacion: 'Áncash, Perú',
                equipo:'UNASAM',
                universidad:'UNASAM',
                especialidad:null,
                descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM) - Ancash. Tengo experiencia en proyectos de investigación relacionados a entornos glaciares con técnicas de fotogrametría, así como teledetección, herramientas GIS y monitoreos ambientales.',
                contacto:{
                    correo:'mailto:elijadiel05@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:null,
                    orcid:'https://orcid.org/0000-0003-1739-8492',
                    researchgate:null,
                },
            },
            {
                user:'1-dfg-edwin-anibal-loarte-cadenas',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Edwin Anibal Loarte Cadenas',
                nameUser:'Edwin Anibal',
                cargo:'Asesor e investigador principal',
                profesion:'Ingeniero Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad: 'Máster universitario en Gestión de Recursos Hídricos.',
                descripcion:'Profesional ligado a la investigación en recursos hídricos, glaciología, el cambio climático, conocimientos de análisis de riesgos sobre los ámbitos glaciares, simulación de desbordes de lagunas, con conocimiento de SIG y teledetección aplicados al estudio y monitoreo de los recursos ambientales, procesamiento de imágenes de satélite ópticas y radar. Estudios en gestión de recursos hídricos; capacitación en el campo de la glaciología e hidroglaciología, elaboración de balances de masa, determinación de líneas de equilibrio - ELA, determinación del área superficial, estimación de volúmenes, generación de índices de nieve - NDSI para coberturar área glaciar, índices de agua NDWI para coberturar lagunas, NDVI para coberturas de vegetación, experiencia en implementación de bases de datos espaciales e inventarios de lagunas.',
                contacto:{
                    correo:'mailto:e.loarte@inaigem.gob.pe, eloartecadenas@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:'https://www.linkedin.com/in/edwin-loarte-cadenas-182b3153/',
                    ctvitae: 'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=19929',
                    orcid:'https://orcid.org/0000-0003-3123-1904',
                }
            },
            {
                user:'2-dfg-rolando-cruz-encarnacion',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Rolando Cesai Cruz Encarnación',
                nameUser:'Rolando Cruz',
                cargo:'Co-Asesor',
                profesion:'Ingeniera Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'ANA',
                especialidad:'Maestría en "Técnicas de Gestión del Medio Ambiente y del Territorio" / (2020) Universitat de València y Diplomado en "Gestión Ambiental" (2016) / Universidad Nacional de Ingeniería.',
                descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (V superior) - Ancash, con experiencia en trabajos con comunidades en los Andes peruanos, sistematización, organización y procesamiento de datos glaciológicos y geomáticos aplicados a recursos hídricos, he participado en proyectos de cooperación internacional,  durante mi carrera profesional he participado de las publicaciones de documentos técnicos y manuales metodológicos para el estudio de los glaciares y los ecosistemas de montaña.',
                contacto:{
                    correo:'mailto:yadira.acr@gmail.com',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:"https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=143570",
                    orcid:"https://orcid.org/0000-0001-8229-2753",
                    researchgate:"https://www.researchgate.net/profile/Yadira-Curo"
                },
            },
            {
                user:'3-dfg-francisco-nemecio-castillo-vergara',
                ruta:'redes-neuronales-profundas',
                foto:'/section/Clima.jpg',
                name:'Francisco Nemecio Castillo Vergara',
                nameUser:'Francisco Castillo',
                cargo:'Asistente de investigación',
                profesion:'Ingeniero Ambiental',
                ubicacion: 'Áncash, Perú',
                universidad:'UNASAM',
                equipo:'UNASAM',
                especialidad:'Especialización en "Modelamiento hidraulico e hidrologico" - CELAEP-UNMSM y Estudios finalizados en maestría en "Ciencias e Ingeniería con mención en Gestión Ambiental" - UNASAM.',
                descripcion:'Ingeniero Ambiental de la UNASAM (quinto superior) dedicado al uso de las herramientas de teledetección y los sistemas de información geográfica. Investigador en proceso de formación en proyectos multidisciplinarios en temáticas relacionadas a ecosistemas glaciares y periglaciares, con conocimiento en el manejo de equipos y técnicas de monitoreo glaciológico. Fotógrafo aficionado y amante del senderismo en altamontaña.',
                contacto:{
                    correo:'mailto:fcastillouv@unasam.edu.pe',
                    email:'Enviar correo',
                },
                redes:{
                    linkedin:null,
                    ctvitae:'https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=351770571c155d27537e1a415bed?id_investigador=145013',
                    orcid:'https://orcid.org/0000-0002-6799-3495',
                    researchgate:null
                },
            },
        ]
    } 
]