import React, { Fragment } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Layout from '../../../../src/layout';
import Nav from '../../../../src/shared/nav/nav';
import {listaTesis} from '../../../../src/lineas/criosfera/proyectos/iat_glaciar/componentes/produccion/lista/lista.tesis';
import Footer from '../../../../src/shared/footer/footer';
import laguna_pequeña from '../../../../public/fondos/Laguna_pequeña.JPG';

export default function Home () {
    const router = useRouter();
    return (
        <Layout>
            <Head>
                <title>Criósfera, Clima y Seguridad Hídrica</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>
            <main>
                <Nav />
                <div className='relative'>
                    <Image className='w-full cover' src={laguna_pequeña} height={1200} alt='Grupo de investigación'/>
                    <Link href='/criosfera/iat_glaciar'>
                        <a>
                            <code><h1 className='flex items-center justify-center lg:hidden absolute bottom-0 left-0 bg-white h-12 w-12 font-bold text-color text-white text-xl'>{`<`}</h1></code>
                        </a>
                    </Link>
                </div>
                <div className='flex justify-center lg:justify-center py-10 lg:py-16 px-4 lg:px-0'>
                    {
                        listaTesis.map((item)=>{
                            if(item.ruta === router.query.pid){
                                return <Fragment>
                                    <div key={item.id} className='flex flex-col-reverse lg:flex-row gap-3 lg:gap-5 flex-1 w-full lg:max-w-6xl'>
                                        <div className='border border-gray-300 rounded-md p-4'>
                                            <Link href='/criosfera/iat_glaciar'>
                                                <a className='h-7'>
                                                    <div className='flex items-center hidden lg:flex'>
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" className="bi bi-arrow-left-short" viewBox="0 0 16 16">
                                                            <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
                                                        </svg>
                                                        <h1 className='text-sm'>Volver</h1>
                                                    </div>
                                                </a>
                                            </Link>
                                            <div className='flex flex-col flex-1 w-full md:max-w-2xl lg:max-w-3xl mt-5'>
                                                <h1 className='font-bold text-xl text-justify'>{item.titulo}</h1>
                                                <h1 className='text-sm mt-1'>Abril del 2023</h1>
                                                <div className='flex gap-2 mt-3'>
                                                    <Link href={`/criosfera/iat_glaciar/equipo/${item.team[0].user}`}><h1 className='cursor-pointer text-sm underline'>{item.team[0].nameUser}</h1></Link>
                                                    <h1>,</h1>
                                                    <Link href={`/criosfera/iat_glaciar/equipo/${item.team[1].user}`}><h1 className='cursor-pointer text-sm underline'>{item.team[1].nameUser}</h1></Link>
                                                    <h1>,</h1>
                                                    <Link href={`/criosfera/iat_glaciar/equipo/${item.team[2].user}`}><h1 className='cursor-pointer text-sm underline'>{item.team[2].nameUser}</h1></Link>
                                                    <h1>,</h1>
                                                    <Link href={`/criosfera/iat_glaciar/equipo/${item.team[3].user}`}><h1 className='cursor-pointer text-sm underline'>{item.team[3].nameUser}</h1></Link>
                                                </div>
                                                <h1 className='mt-5 font-bold'>Planteamiento del problema</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip.descrip1 === null?'hidden':'block'} `}>{item.descrip.descrip1}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip.descrip2 === null?'hidden':'block'} `}>{item.descrip.descrip2}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip.descrip3 === null?'hidden':'block'} `}>{item.descrip.descrip3}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip.descrip4 === null?'hidden':'block'} `}>{item.descrip.descrip4}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip.descrip5 === null?'hidden':'block'} `}>{item.descrip.descrip5}</h1>
                                                <h1 className={`mt-2 text-justify ${item.descrip.descrip6 === null?'hidden':'block'} `}>{item.descrip.descrip6}</h1>
                                            </div>
                                        </div>
                                        <div className='w-full lg:flex-1'>
                                            <div className='border border-gray-300 rounded-md'>
                                                <div className='border-b border-gray-300 px-5 py-3'><h1 className='font-bold'>Temas abordados</h1></div>
                                                <div className='p-5'>
                                                    <h1>{item.temas.tema1}</h1>
                                                    <h1>{item.temas.tema2}</h1>
                                                    <h1>{item.temas.tema3}</h1>
                                                    <h1>{item.temas.tema4}</h1>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </Fragment>
                            }
                        })
                    }
                </div>
                <Footer />
            </main>
        </Layout>
    )
}