export const listaTeam= [
    {
        id:1,
        foto:'/section/Clima.JPG',
        user:'edwin-anibal-loarte-cadenas',
        name:'Edwin Anibal Loarte Cadenas',
        cargo:'Asesor e investigador principal',
        profesion:'Ingeniero Ambiental',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'UNASAM',
        especialidad: 'Máster universitario en Gestión de Recursos Hídricos.',
        descripcion:'Profesional ligado a la investigación en recursos hídricos, glaciología, el cambio climático, conocimientos de análisis de riesgos sobre los ámbitos glaciares, simulación de desbordes de lagunas, con conocimiento de SIG y teledetección aplicados al estudio y monitoreo de los recursos ambientales, procesamiento de imágenes de satélite ópticas y radar. Estudios en gestión de recursos hídricos; capacitación en el campo de la glaciología e hidroglaciología, elaboración de balances de masa, determinación de líneas de equilibrio - ELA, determinación del área superficial, estimación de volúmenes, generación de índices de nieve - NDSI para coberturar área glaciar, índices de agua NDWI para coberturar lagunas, NDVI para coberturas de vegetación, experiencia en implementación de bases de datos espaciales e inventarios de lagunas.',
        contacto:{
            correo:'mailto:e.loarte@inaigem.gob.pe, eloartecadenas@gmail.com',
            email:'Enviar correo',
        },
        redes:{
            linkedin:'https://www.linkedin.com/in/edwin-loarte-cadenas-182b3153/',
            ctvitae: 'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=19929',
            orcid:'https://orcid.org/0000-0003-3123-1904',
        }
    },
    {
        id:2,
        foto:'/section/Clima.JPG',
        user:'rolando-cesai-cruz-encarnacion',
        name:'Rolando Cesai Cruz Encarnación',
        cargo:'Co-Asesor',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'ANA',
        profesion:'Ingeniero Ambiental',
        especialidad:'Maestría en "Técnicas de Gestión del Medio Ambiente y del Territorio" / (2020) Universitat de València y Diplomado en "Gestión Ambiental" (2016) / Universidad Nacional de Ingeniería.',
        descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (V superior) - Ancash, con experiencia en trabajos con comunidades en los Andes peruanos, sistematización, organización y procesamiento de datos glaciológicos y geomáticos aplicados a recursos hídricos, he participado en proyectos de cooperación internacional,  durante mi carrera profesional he participado de las publicaciones de documentos técnicos y manuales metodológicos para el estudio de los glaciares y los ecosistemas de montaña.',
        contacto:{
                correo:'mailto:yadira.acr@gmail.com',
                email:'Enviar correo',
        },
        redes:{
            linkedin:null,
            ctvitae:"https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=143570",
            orcid:"https://orcid.org/0000-0001-8229-2753",
            researchgate:"https://www.researchgate.net/profile/Yadira-Curo"
        },
    },
    {
        id:3,
        foto:'/section/Clima.JPG',
        user:'francisco-nemecio-castillo-vergara',
        name:'Francisco Nemecio Castillo Vergara',
        cargo:'Asistente de investigación',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'UNASAM',
        profesion:'Ingeniero Ambiental',
        especialidad:'Especialización en "Modelamiento hidraulico e hidrologico" - CELAEP-UNMSM y Estudios finalizados en maestría en "Ciencias e Ingeniería con mención en Gestión Ambiental" - UNASAM.',
        descripcion:'Ingeniero Ambiental de la UNASAM (quinto superior) dedicado al uso de las herramientas de teledetección y los sistemas de información geográfica. Investigador en proceso de formación en proyectos multidisciplinarios en temáticas relacionadas a ecosistemas glaciares y periglaciares, con conocimiento en el manejo de equipos y técnicas de monitoreo glaciológico. Fotógrafo aficionado y amante del senderismo en altamontaña.',
        contacto:{
            correo:'mailto:fcastillouv@unasam.edu.pe',
            email:'Enviar correo',
        },
        redes:{
            linkedin:null,
            ctvitae:'https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=351770571c155d27537e1a415bed?id_investigador=145013',
            orcid:'https://orcid.org/0000-0002-6799-3495',
            researchgate:null
        },
    },
    {
        id:4,
        foto:'/section/Clima.JPG',
        user:'emely-consuelo-barreto-jamanca',
        name:'Emely Consuelo Barrreto Jamanca',
        cargo:'Tesista de pregrado',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'UNASAM',
        profesion:'Ingeniera Ambiental',
        especialidad:null,
        descripcion:'Ingeniera Ambiental de la UNASAM (V superior) - Ancash. Experiencia en estudios de ecología. Participación en proyectos de investigación enfocados al estudio de ecosistemas de montaña, así como en biodiversidad en bosques xéricos y andinos. Conocimiento en tecnologías GIS, manejo de herramientas de estadística ecológica y estimación de la biodiversidad.',
        contacto:{
            correo:'mailto:mp.alejo.mosquera@gmail.com',
            email:'Enviar correo',
        },
        redes:{
            linkedin:"https://www.linkedin.com/in/miluska-pamela-alejo-mosquera-91a2bb223",
            ctvitae:"https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=274222",
            orcid:"https://orcid.org/0000-0002-6510-7875 ",
            researchgate:null
        },
    },
    {
        id:5,
        user:'thalia-yanina-calixto-lopez',
        ruta:'Determinación-del-nivel-de-influencia-de-la-temperatura-en-la-variación-de-los-espesores-de-los-frentes-glaciares-en-la-Cordillera-Blanca',
        foto:'/section/Clima.JPG',
        name:'Thalía Yanina Calixto Lopez',
        nameUser:'Thalía Calixto',
        cargo:'Tesista de pregrado',
        profesion:'Ingeniera Ambiental',
        ubicacion: 'Áncash, Perú',
        equipo:'UNASAM',
        universidad:'UNASAM',
        especialidad:null,
        descripcion:'Ingeniera Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM) - Ancash. Tengo experiencia en proyectos de investigación relacionados a entornos glaciares con técnicas de fotogrametría, así como teledetección, herramientas GIS y monitoreos ambientales.',
        contacto:{
            correo:'mailto:elijadiel05@gmail.com',
            email:'Enviar correo',
        },
        redes:{
            linkedin:null,
            ctvitae:null,
            orcid:'https://orcid.org/0000-0003-1739-8492',
            researchgate:null,
        },
    },
    {
        id:6,
        foto:'/section/Clima.JPG',
        user:'victor-smith-medina-cotrina',
        name:'Víctor Smith Medina Cotrina',
        cargo:'Tesista de pregrado',
        profesion:'Bachiller en Ingeniería Ambiental',
        especialidad:null,
        descripcion:'Bachiller en ingeniería ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM), un apasionado por el aprendizaje automático y la ciencia de datos para la comprensión, monitoreo y predección del cambio ambiental. Particularmente interesado en la programación en redes neuronales artificiales, clasificación de imágenes y detección de objetos aplicados a la investigación en glaciares y a la conservación de Áreas Naturales Protegidas (ANPs).',
        ubicacion:'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'UNASAM',
        contacto:{
            correo:'mailto:smith_12_47@hotmail.com',
            email:'Enviar correo',
        },
        redes:{
            linkedin:'https://www.linkedin.com/in/v%C3%ADctor-smith-medina-cotrina-28155159/',
        }
    },
]