import Head from 'next/head'
import Layout from '../src/layout';
import IndexClima from '../src/lineas/clima/clima';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Criósfera, Clima y Seguridad Hídrica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexClima />
    </Layout>
  )
}
